### PR TITLE
CLI file added.

### PR DESCRIPTION
**Pull request by saberprashant**
Hey, I've added a new pdf_audio_CLI.py for the project as mentioned in open issues( CMoC ).

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
Good job Prashant.
It would be better if you add a few more optional arguments to CLI like:
- rate of speech
- type of voice

You can tweak them here:
```
engine.setProperty('rate', 150)
engine.setProperty('voice', 'en+m7')
```
Keep them as -r and -v.
Also, remove -s argument and make it positional.

**Comment by saberprashant** [comment]
Nice idea... I will add them soon and will get back to you ;)

**Comment by saberprashant** [comment]
Hey, I've added what you proposed, check it out 👍

**Comment by saberprashant** [comment]
Hi Nikhil,
Can you please close those issues which are done by me?

**Pull request merged**
